version: '3'

services:
  registry:
    image: registry:2
    container_name: registry
    volumes:
      - registry:/var/lib/registry
    restart: unless-stopped
  shellinabox:
    build: ./shellinabox
    container_name: shellinabox
    environment:
      - SHELLINABOX_DEFAULT=host
      - SHELLINABOX_SERVICE_HOST=host
      - SHELLINABOX_SERVICE_WHO=who
      - SHELLINABOX_ALLOW_SUDO=1
      - SHELLINABOX_DISABLE_SSL=1
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
      - JAVA_OPTS=${JAVA_OPTS:-'-Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-scripts;"'}
    restart: unless-stopped
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/nginx/html:/usr/share/nginx/html:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    image: mysql
    volumes:
      - data_db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
  wordpress:
    image: wordpress
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    volumes:
     - ./data/wordpress:/var/www/html/wp-content
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=wordpress
      - PMA_ABSOLUTE_URI=https://test.trainamon.com/pma/
volumes:
  jenkins_home:
  portainer_data:
  registry:
  data_db:
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
